# compose.local.yml (override local)
services:
  trxbewi_cam:
    image: iobewi:trxbewi_cam
    devices:
      - /dev/media0:/dev/media0 
      - /dev/media1:/dev/media1
      - /dev/media2:/dev/media2
      - /dev/v4l-subdev0:/dev/v4l-subdev0
      - /dev/v4l-subdev1:/dev/v4l-subdev1
      - /dev/v4l-subdev2:/dev/v4l-subdev2
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5
      - /dev/video6:/dev/video6
      - /dev/video7:/dev/video7
      - /dev/video19:/dev/video19
      - /dev/video20:/dev/video20
      - /dev/video21:/dev/video21
      - /dev/video22:/dev/video22
      - /dev/video23:/dev/video23
      - /dev/video24:/dev/video24
      - /dev/video25:/dev/video25
      - /dev/video26:/dev/video26
      - /dev/video27:/dev/video27
      - /dev/video28:/dev/video28
      - /dev/video29:/dev/video29
      - /dev/video30:/dev/video30
      - /dev/video31:/dev/video31
      - /dev/video32:/dev/video32
      - /dev/video33:/dev/video33
      - /dev/video34:/dev/video34
      - /dev/video35:/dev/video35
    security_opt:
      - no-new-privileges:true   # pas --privileged